///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Calculator_testing
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Calculator_testingRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("2590afdc-baf2-4f86-af91-d3dc88cc04e5")]
    public partial class Calculator_testingRepository : RepoGenBaseFolder
    {
        static Calculator_testingRepository instance = new Calculator_testingRepository();
        Calculator_testingRepositoryFolders.КалькуляторAppFolder _калькулятор;

        /// <summary>
        /// Gets the singleton class instance representing the Calculator_testingRepository element repository.
        /// </summary>
        [RepositoryFolder("2590afdc-baf2-4f86-af91-d3dc88cc04e5")]
        public static Calculator_testingRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Calculator_testingRepository() 
            : base("Calculator_testingRepository", "/", null, 0, false, "2590afdc-baf2-4f86-af91-d3dc88cc04e5", ".\\RepositoryImages\\Calculator_testingRepository2590afdc.rximgres")
        {
            _калькулятор = new Calculator_testingRepositoryFolders.КалькуляторAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("2590afdc-baf2-4f86-af91-d3dc88cc04e5")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Калькулятор folder.
        /// </summary>
        [RepositoryFolder("0f52ff72-d2f2-4af5-bd78-3784ab2a9cfa")]
        public virtual Calculator_testingRepositoryFolders.КалькуляторAppFolder Калькулятор
        {
            get { return _калькулятор; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Calculator_testingRepositoryFolders
    {
        /// <summary>
        /// The КалькуляторAppFolder folder.
        /// </summary>
        [RepositoryFolder("0f52ff72-d2f2-4af5-bd78-3784ab2a9cfa")]
        public partial class КалькуляторAppFolder : RepoGenBaseFolder
        {
            Calculator_testingRepositoryFolders.SomeContainerFolder _somecontainer;

            /// <summary>
            /// Creates a new Калькулятор  folder.
            /// </summary>
            public КалькуляторAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Калькулятор", "/form[@automationid='']", parentFolder, 30000, null, true, "0f52ff72-d2f2-4af5-bd78-3784ab2a9cfa", "")
            {
                _somecontainer = new Calculator_testingRepositoryFolders.SomeContainerFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0f52ff72-d2f2-4af5-bd78-3784ab2a9cfa")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0f52ff72-d2f2-4af5-bd78-3784ab2a9cfa")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SomeContainer folder.
            /// </summary>
            [RepositoryFolder("aeab7223-ab3f-40f0-88be-2d276c2b09e9")]
            public virtual Calculator_testingRepositoryFolders.SomeContainerFolder SomeContainer
            {
                get { return _somecontainer; }
            }
        }

        /// <summary>
        /// The SomeContainerFolder folder.
        /// </summary>
        [RepositoryFolder("aeab7223-ab3f-40f0-88be-2d276c2b09e9")]
        public partial class SomeContainerFolder : RepoGenBaseFolder
        {
            RepoItemInfo _button1Info;
            RepoItemInfo _button2Info;
            RepoItemInfo _button3Info;
            RepoItemInfo _buttonplusInfo;
            RepoItemInfo _buttonplus1Info;
            RepoItemInfo _button0Info;
            RepoItemInfo _buttonInfo;
            RepoItemInfo _buttoneqInfo;
            RepoItemInfo _button4Info;
            RepoItemInfo _button5Info;
            RepoItemInfo _button6Info;
            RepoItemInfo _button7Info;
            RepoItemInfo _button71Info;
            RepoItemInfo _button8Info;
            RepoItemInfo _button9Info;
            RepoItemInfo _buttonasteriskInfo;
            RepoItemInfo _button1xInfo;
            RepoItemInfo _buttonxsqInfo;
            RepoItemInfo _buttonxInfo;
            RepoItemInfo _button10Info;
            RepoItemInfo _buttonpercentInfo;
            RepoItemInfo _buttoncInfo;
            RepoItemInfo _backspaseInfo;

            /// <summary>
            /// Creates a new SomeContainer  folder.
            /// </summary>
            public SomeContainerFolder(RepoGenBaseFolder parentFolder) :
                    base("SomeContainer", "container[1]", parentFolder, 30000, null, false, "aeab7223-ab3f-40f0-88be-2d276c2b09e9", "")
            {
                _button1Info = new RepoItemInfo(this, "Button1", "?/?/button[@text='1']", "", 30000, null, "0c15a6c6-9e67-4869-8189-6cc966b8948a");
                _button2Info = new RepoItemInfo(this, "Button2", "?/?/button[@text='2']", "", 30000, null, "7209fbb2-68fc-4d3d-bfb2-40f6daccf6b2");
                _button3Info = new RepoItemInfo(this, "Button3", "?/?/button[@text='3']", "", 30000, null, "aeae2124-24f8-4908-9101-e8b73ca1cf3c");
                _buttonplusInfo = new RepoItemInfo(this, "ButtonPlus", "?/?/button[@text='+']", "", 30000, null, "a380d02e-e144-483f-a0bd-06ab3ef5a536");
                _buttonplus1Info = new RepoItemInfo(this, "ButtonPlus1", "?/?/button[@text='+/-']", "", 30000, null, "961a7a6f-58c0-467b-b15c-e8fdc3445212");
                _button0Info = new RepoItemInfo(this, "Button0", "?/?/button[@text='0']", "", 30000, null, "896ec635-5619-4832-b0ca-1580776201ea");
                _buttonInfo = new RepoItemInfo(this, "Button", "?/?/button[@text=',']", "", 30000, null, "0ff6be21-4f2e-44cf-b177-ecae1bb7d9ba");
                _buttoneqInfo = new RepoItemInfo(this, "ButtonEq", "?/?/button[@text='=']", "", 30000, null, "6ef76179-7007-4d54-847c-01d269d31697");
                _button4Info = new RepoItemInfo(this, "Button4", "?/?/button[@text='4']", "", 30000, null, "c7785bbc-7569-4937-8b7e-b06517192f32");
                _button5Info = new RepoItemInfo(this, "Button5", "?/?/button[@text='5']", "", 30000, null, "a03ad15e-3a25-4041-8274-629ca4f51459");
                _button6Info = new RepoItemInfo(this, "Button6", "?/?/button[@text='6']", "", 30000, null, "5a84b321-bb2c-4e2e-94b2-59fe664e2397");
                _button7Info = new RepoItemInfo(this, "Button7", "?/?/button[@text='-']", "", 30000, null, "ea0f5da6-c8a6-4659-9de1-4894f45c335b");
                _button71Info = new RepoItemInfo(this, "Button71", "?/?/button[@text='7']", "", 30000, null, "85472f94-460e-457e-b4ed-2ff155ac82c1");
                _button8Info = new RepoItemInfo(this, "Button8", "?/?/button[@text='8']", "", 30000, null, "1845952d-4177-4dbb-934a-7417f07ed501");
                _button9Info = new RepoItemInfo(this, "Button9", "?/?/button[@text='9']", "", 30000, null, "4759b044-1934-4dcf-9535-896e64675a71");
                _buttonasteriskInfo = new RepoItemInfo(this, "ButtonAsterisk", "?/?/button[@text='*']", "", 30000, null, "1421b3e7-ad11-40bb-8752-ec08074eec42");
                _button1xInfo = new RepoItemInfo(this, "Button1X", "?/?/button[@text='1/x']", "", 30000, null, "b7093bc9-7f4c-43e0-bc8a-92c1b4468009");
                _buttonxsqInfo = new RepoItemInfo(this, "ButtonXSq", "?/?/button[@text='x²']", "", 30000, null, "65e1588f-defc-4376-981f-c6e821477ae1");
                _buttonxInfo = new RepoItemInfo(this, "ButtonX", "?/?/button[@text='√x']", "", 30000, null, "2ec03a9e-6bd4-40df-abc4-a1f46e532f5a");
                _button10Info = new RepoItemInfo(this, "Button10", "?/?/button[@text='/']", "", 30000, null, "a9fb46a8-3bf3-4a71-81f2-952989e21ce9");
                _buttonpercentInfo = new RepoItemInfo(this, "ButtonPercent", "?/?/button[@text='%']", "", 30000, null, "cd622cfc-3a1f-4260-942e-9485918c7937");
                _buttoncInfo = new RepoItemInfo(this, "ButtonC", "?/?/button[@text='C']", "", 30000, null, "bcf57b3e-bdee-4e23-be30-06cf57824b3b");
                _backspaseInfo = new RepoItemInfo(this, "Backspase", "?/?/button[@text='Backspase']", "", 30000, null, "e0fc1476-8db1-4dcb-9433-04cd55d31ab5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("aeab7223-ab3f-40f0-88be-2d276c2b09e9")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("aeab7223-ab3f-40f0-88be-2d276c2b09e9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Button1 item.
            /// </summary>
            [RepositoryItem("0c15a6c6-9e67-4869-8189-6cc966b8948a")]
            public virtual Ranorex.Button Button1
            {
                get
                {
                    return _button1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button1 item info.
            /// </summary>
            [RepositoryItemInfo("0c15a6c6-9e67-4869-8189-6cc966b8948a")]
            public virtual RepoItemInfo Button1Info
            {
                get
                {
                    return _button1Info;
                }
            }

            /// <summary>
            /// The Button2 item.
            /// </summary>
            [RepositoryItem("7209fbb2-68fc-4d3d-bfb2-40f6daccf6b2")]
            public virtual Ranorex.Button Button2
            {
                get
                {
                    return _button2Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button2 item info.
            /// </summary>
            [RepositoryItemInfo("7209fbb2-68fc-4d3d-bfb2-40f6daccf6b2")]
            public virtual RepoItemInfo Button2Info
            {
                get
                {
                    return _button2Info;
                }
            }

            /// <summary>
            /// The Button3 item.
            /// </summary>
            [RepositoryItem("aeae2124-24f8-4908-9101-e8b73ca1cf3c")]
            public virtual Ranorex.Button Button3
            {
                get
                {
                    return _button3Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button3 item info.
            /// </summary>
            [RepositoryItemInfo("aeae2124-24f8-4908-9101-e8b73ca1cf3c")]
            public virtual RepoItemInfo Button3Info
            {
                get
                {
                    return _button3Info;
                }
            }

            /// <summary>
            /// The ButtonPlus item.
            /// </summary>
            [RepositoryItem("a380d02e-e144-483f-a0bd-06ab3ef5a536")]
            public virtual Ranorex.Button ButtonPlus
            {
                get
                {
                    return _buttonplusInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonPlus item info.
            /// </summary>
            [RepositoryItemInfo("a380d02e-e144-483f-a0bd-06ab3ef5a536")]
            public virtual RepoItemInfo ButtonPlusInfo
            {
                get
                {
                    return _buttonplusInfo;
                }
            }

            /// <summary>
            /// The ButtonPlus1 item.
            /// </summary>
            [RepositoryItem("961a7a6f-58c0-467b-b15c-e8fdc3445212")]
            public virtual Ranorex.Button ButtonPlus1
            {
                get
                {
                    return _buttonplus1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonPlus1 item info.
            /// </summary>
            [RepositoryItemInfo("961a7a6f-58c0-467b-b15c-e8fdc3445212")]
            public virtual RepoItemInfo ButtonPlus1Info
            {
                get
                {
                    return _buttonplus1Info;
                }
            }

            /// <summary>
            /// The Button0 item.
            /// </summary>
            [RepositoryItem("896ec635-5619-4832-b0ca-1580776201ea")]
            public virtual Ranorex.Button Button0
            {
                get
                {
                    return _button0Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button0 item info.
            /// </summary>
            [RepositoryItemInfo("896ec635-5619-4832-b0ca-1580776201ea")]
            public virtual RepoItemInfo Button0Info
            {
                get
                {
                    return _button0Info;
                }
            }

            /// <summary>
            /// The Button item.
            /// </summary>
            [RepositoryItem("0ff6be21-4f2e-44cf-b177-ecae1bb7d9ba")]
            public virtual Ranorex.Button Button
            {
                get
                {
                    return _buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button item info.
            /// </summary>
            [RepositoryItemInfo("0ff6be21-4f2e-44cf-b177-ecae1bb7d9ba")]
            public virtual RepoItemInfo ButtonInfo
            {
                get
                {
                    return _buttonInfo;
                }
            }

            /// <summary>
            /// The ButtonEq item.
            /// </summary>
            [RepositoryItem("6ef76179-7007-4d54-847c-01d269d31697")]
            public virtual Ranorex.Button ButtonEq
            {
                get
                {
                    return _buttoneqInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonEq item info.
            /// </summary>
            [RepositoryItemInfo("6ef76179-7007-4d54-847c-01d269d31697")]
            public virtual RepoItemInfo ButtonEqInfo
            {
                get
                {
                    return _buttoneqInfo;
                }
            }

            /// <summary>
            /// The Button4 item.
            /// </summary>
            [RepositoryItem("c7785bbc-7569-4937-8b7e-b06517192f32")]
            public virtual Ranorex.Button Button4
            {
                get
                {
                    return _button4Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button4 item info.
            /// </summary>
            [RepositoryItemInfo("c7785bbc-7569-4937-8b7e-b06517192f32")]
            public virtual RepoItemInfo Button4Info
            {
                get
                {
                    return _button4Info;
                }
            }

            /// <summary>
            /// The Button5 item.
            /// </summary>
            [RepositoryItem("a03ad15e-3a25-4041-8274-629ca4f51459")]
            public virtual Ranorex.Button Button5
            {
                get
                {
                    return _button5Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button5 item info.
            /// </summary>
            [RepositoryItemInfo("a03ad15e-3a25-4041-8274-629ca4f51459")]
            public virtual RepoItemInfo Button5Info
            {
                get
                {
                    return _button5Info;
                }
            }

            /// <summary>
            /// The Button6 item.
            /// </summary>
            [RepositoryItem("5a84b321-bb2c-4e2e-94b2-59fe664e2397")]
            public virtual Ranorex.Button Button6
            {
                get
                {
                    return _button6Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button6 item info.
            /// </summary>
            [RepositoryItemInfo("5a84b321-bb2c-4e2e-94b2-59fe664e2397")]
            public virtual RepoItemInfo Button6Info
            {
                get
                {
                    return _button6Info;
                }
            }

            /// <summary>
            /// The Button7 item.
            /// </summary>
            [RepositoryItem("ea0f5da6-c8a6-4659-9de1-4894f45c335b")]
            public virtual Ranorex.Button Button7
            {
                get
                {
                    return _button7Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button7 item info.
            /// </summary>
            [RepositoryItemInfo("ea0f5da6-c8a6-4659-9de1-4894f45c335b")]
            public virtual RepoItemInfo Button7Info
            {
                get
                {
                    return _button7Info;
                }
            }

            /// <summary>
            /// The Button71 item.
            /// </summary>
            [RepositoryItem("85472f94-460e-457e-b4ed-2ff155ac82c1")]
            public virtual Ranorex.Button Button71
            {
                get
                {
                    return _button71Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button71 item info.
            /// </summary>
            [RepositoryItemInfo("85472f94-460e-457e-b4ed-2ff155ac82c1")]
            public virtual RepoItemInfo Button71Info
            {
                get
                {
                    return _button71Info;
                }
            }

            /// <summary>
            /// The Button8 item.
            /// </summary>
            [RepositoryItem("1845952d-4177-4dbb-934a-7417f07ed501")]
            public virtual Ranorex.Button Button8
            {
                get
                {
                    return _button8Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button8 item info.
            /// </summary>
            [RepositoryItemInfo("1845952d-4177-4dbb-934a-7417f07ed501")]
            public virtual RepoItemInfo Button8Info
            {
                get
                {
                    return _button8Info;
                }
            }

            /// <summary>
            /// The Button9 item.
            /// </summary>
            [RepositoryItem("4759b044-1934-4dcf-9535-896e64675a71")]
            public virtual Ranorex.Button Button9
            {
                get
                {
                    return _button9Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button9 item info.
            /// </summary>
            [RepositoryItemInfo("4759b044-1934-4dcf-9535-896e64675a71")]
            public virtual RepoItemInfo Button9Info
            {
                get
                {
                    return _button9Info;
                }
            }

            /// <summary>
            /// The ButtonAsterisk item.
            /// </summary>
            [RepositoryItem("1421b3e7-ad11-40bb-8752-ec08074eec42")]
            public virtual Ranorex.Button ButtonAsterisk
            {
                get
                {
                    return _buttonasteriskInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonAsterisk item info.
            /// </summary>
            [RepositoryItemInfo("1421b3e7-ad11-40bb-8752-ec08074eec42")]
            public virtual RepoItemInfo ButtonAsteriskInfo
            {
                get
                {
                    return _buttonasteriskInfo;
                }
            }

            /// <summary>
            /// The Button1X item.
            /// </summary>
            [RepositoryItem("b7093bc9-7f4c-43e0-bc8a-92c1b4468009")]
            public virtual Ranorex.Button Button1X
            {
                get
                {
                    return _button1xInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button1X item info.
            /// </summary>
            [RepositoryItemInfo("b7093bc9-7f4c-43e0-bc8a-92c1b4468009")]
            public virtual RepoItemInfo Button1XInfo
            {
                get
                {
                    return _button1xInfo;
                }
            }

            /// <summary>
            /// The ButtonXSq item.
            /// </summary>
            [RepositoryItem("65e1588f-defc-4376-981f-c6e821477ae1")]
            public virtual Ranorex.Button ButtonXSq
            {
                get
                {
                    return _buttonxsqInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonXSq item info.
            /// </summary>
            [RepositoryItemInfo("65e1588f-defc-4376-981f-c6e821477ae1")]
            public virtual RepoItemInfo ButtonXSqInfo
            {
                get
                {
                    return _buttonxsqInfo;
                }
            }

            /// <summary>
            /// The ButtonX item.
            /// </summary>
            [RepositoryItem("2ec03a9e-6bd4-40df-abc4-a1f46e532f5a")]
            public virtual Ranorex.Button ButtonX
            {
                get
                {
                    return _buttonxInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonX item info.
            /// </summary>
            [RepositoryItemInfo("2ec03a9e-6bd4-40df-abc4-a1f46e532f5a")]
            public virtual RepoItemInfo ButtonXInfo
            {
                get
                {
                    return _buttonxInfo;
                }
            }

            /// <summary>
            /// The Button10 item.
            /// </summary>
            [RepositoryItem("a9fb46a8-3bf3-4a71-81f2-952989e21ce9")]
            public virtual Ranorex.Button Button10
            {
                get
                {
                    return _button10Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button10 item info.
            /// </summary>
            [RepositoryItemInfo("a9fb46a8-3bf3-4a71-81f2-952989e21ce9")]
            public virtual RepoItemInfo Button10Info
            {
                get
                {
                    return _button10Info;
                }
            }

            /// <summary>
            /// The ButtonPercent item.
            /// </summary>
            [RepositoryItem("cd622cfc-3a1f-4260-942e-9485918c7937")]
            public virtual Ranorex.Button ButtonPercent
            {
                get
                {
                    return _buttonpercentInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonPercent item info.
            /// </summary>
            [RepositoryItemInfo("cd622cfc-3a1f-4260-942e-9485918c7937")]
            public virtual RepoItemInfo ButtonPercentInfo
            {
                get
                {
                    return _buttonpercentInfo;
                }
            }

            /// <summary>
            /// The ButtonC item.
            /// </summary>
            [RepositoryItem("bcf57b3e-bdee-4e23-be30-06cf57824b3b")]
            public virtual Ranorex.Button ButtonC
            {
                get
                {
                    return _buttoncInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonC item info.
            /// </summary>
            [RepositoryItemInfo("bcf57b3e-bdee-4e23-be30-06cf57824b3b")]
            public virtual RepoItemInfo ButtonCInfo
            {
                get
                {
                    return _buttoncInfo;
                }
            }

            /// <summary>
            /// The Backspase item.
            /// </summary>
            [RepositoryItem("e0fc1476-8db1-4dcb-9433-04cd55d31ab5")]
            public virtual Ranorex.Button Backspase
            {
                get
                {
                    return _backspaseInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Backspase item info.
            /// </summary>
            [RepositoryItemInfo("e0fc1476-8db1-4dcb-9433-04cd55d31ab5")]
            public virtual RepoItemInfo BackspaseInfo
            {
                get
                {
                    return _backspaseInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
