///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Calculator_testing
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The TestSummPuPf recording.
    /// </summary>
    [TestModule("6e299aa2-f0c8-402b-bfa3-4682f4740b64", ModuleType.Recording, 1)]
    public partial class TestSummPuPf : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Calculator_testingRepository repository.
        /// </summary>
        public static Calculator_testingRepository repo = Calculator_testingRepository.Instance;

        static TestSummPuPf instance = new TestSummPuPf();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public TestSummPuPf()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static TestSummPuPf Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Калькулятор.SomeContainer.Button1' at 95;17.", repo.Калькулятор.SomeContainer.Button1Info, new RecordItemIndex(0));
            repo.Калькулятор.SomeContainer.Button1.Click("95;17");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Калькулятор.SomeContainer.ButtonPlus' at 16;13.", repo.Калькулятор.SomeContainer.ButtonPlusInfo, new RecordItemIndex(1));
            repo.Калькулятор.SomeContainer.ButtonPlus.Click("16;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Калькулятор.SomeContainer.Button3' at 76;34.", repo.Калькулятор.SomeContainer.Button3Info, new RecordItemIndex(2));
            repo.Калькулятор.SomeContainer.Button3.Click("76;34");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Калькулятор.SomeContainer.Button' at 89;27.", repo.Калькулятор.SomeContainer.ButtonInfo, new RecordItemIndex(3));
            repo.Калькулятор.SomeContainer.Button.Click("89;27");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Калькулятор.SomeContainer.Button2' at 93;42.", repo.Калькулятор.SomeContainer.Button2Info, new RecordItemIndex(4));
            repo.Калькулятор.SomeContainer.Button2.Click("93;42");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Калькулятор.SomeContainer.ButtonEq' at 41;19.", repo.Калькулятор.SomeContainer.ButtonEqInfo, new RecordItemIndex(5));
            repo.Калькулятор.SomeContainer.ButtonEq.Click("41;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Калькулятор.SomeContainer.ButtonC' at 43;14.", repo.Калькулятор.SomeContainer.ButtonCInfo, new RecordItemIndex(6));
            repo.Калькулятор.SomeContainer.ButtonC.Click("43;14");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
